### ISSUE TITLE
Enchantment Shulker-Like attempting to apply to modded items failing with log spam

### ISSUE THREAD

**Issue by NighthowlerStudios** [Ephys/mc-shulker-enchantments#7]
```
[13:10:08] [Render thread/ERROR]: Failed to determine enchantment compatibility for Item "spartanweaponry:glaive_stone" from the "Spartan Weaponry" mod.
[13:10:08] [Render thread/ERROR]: Catching
java.lang.IllegalStateException: Tag shulker_enchantments:shulker_like used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?]
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?]
	at net.minecraft.item.Item.func_206844_a(Item.java:343) ~[?:?]
	at be.ephys.shulker_enchantments.ShulkerLikeTag.isShulkerLike(ShulkerLikeTag.java:15) ~[?:2.1.1]
	at be.ephys.shulker_enchantments.siphon.SiphonEnchantment.func_92089_a(SiphonEnchantment.java:43) ~[?:2.1.1]
	at net.darkhax.enchdesc.jei.EnchantmentInfoEntry.buildCompatibilityCache(EnchantmentInfoEntry.java:149) [?:7.0.17]
	at net.darkhax.enchdesc.jei.EnchantmentInfoEntry.getCompatibleItems(EnchantmentInfoEntry.java:125) [?:7.0.17]
	at net.darkhax.enchdesc.jei.EnchantmentInfoEntry.<init>(EnchantmentInfoEntry.java:48) [?:7.0.17]
	at net.darkhax.enchdesc.jei.EnchantmentDescriptionsJEIPlugin$$Lambda$25455/984101138.apply(Unknown Source) [?:7.0.17]
```

this bloats my log file to around 10MB but only on the client side (dedicated server does not have this issue)

it seems to be trying to apply this enchantment to every item possible, this is just a snippet of one item amongst thousands

**Comment by NighthowlerStudios** [comment]
This bug also leads to, for whatever reason, packet corruption from server to client, that results in blocks having wrong id's, a native memory leak with an eventual client lockup.   I have no clue why that's the case, only knowledge that it broke my pack horribly somehow.

**Comment by ephys** [comment]
I'm not sure this is a bug from this mod. Enchdesc is trying to build the table of which enchantment can be applied to what item before item tags have had time to initialize. I'm using item tags to determine what items support shulker enchantments.

They're building their compat table too early.

**Comment by NighthowlerStudios** [comment]
strange, considering removing this mod is what fixed my pack's packet corruption.

it's possible the bug is a thread race issue during registry, causing it to memory leak stack stuff because the thread never stops or something.

**Comment by NighthowlerStudios** [comment]
to be clear, this issue only started happening after the recent fix release for lootr compat (2.1.1) so I think removing your property injection broke enchantment descriptions' registry system
